#if !canImport(ObjectiveC)
import XCTest

extension OrderedDictionaryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderedDictionaryTests = [
        ("testAccessingContent", testAccessingContent),
        ("testAccessingOrderedKeys", testAccessingOrderedKeys),
        ("testAccessingOrderedValues", testAccessingOrderedValues),
        ("testAccessingUnsortedDictionary", testAccessingUnsortedDictionary),
        ("testCapacityGrowForElementInsertion", testCapacityGrowForElementInsertion),
        ("testCapacityReservationViaInit", testCapacityReservationViaInit),
        ("testCapacityReservationViaMethod", testCapacityReservationViaMethod),
        ("testCompactMapValues", testCompactMapValues),
        ("testCreatingIterator", testCreatingIterator),
        ("testCreationFromDictionary", testCreationFromDictionary),
        ("testDebugDescription", testDebugDescription),
        ("testDescription", testDescription),
        ("testEmptyDebugDescription", testEmptyDebugDescription),
        ("testEmptyDescription", testEmptyDescription),
        ("testEncodingAndDecodingViaJSON", testEncodingAndDecodingViaJSON),
        ("testEncodingAndDecodingViaPropertyList", testEncodingAndDecodingViaPropertyList),
        ("testIndexBasedInsertionsWithUniqueKeys", testIndexBasedInsertionsWithUniqueKeys),
        ("testIndexBasedInsertionWithDuplicateKey", testIndexBasedInsertionWithDuplicateKey),
        ("testIndexBasedInsertionWithIndexOutOfBounds", testIndexBasedInsertionWithIndexOutOfBounds),
        ("testIndexBasedInsertionWithNegativeIndex", testIndexBasedInsertionWithNegativeIndex),
        ("testIndexBasedRemoval", testIndexBasedRemoval),
        ("testIndexBasedUpdateMethodByDuplicatingKey", testIndexBasedUpdateMethodByDuplicatingKey),
        ("testIndexBasedUpdateMethodByReplacingSameKey", testIndexBasedUpdateMethodByReplacingSameKey),
        ("testIndexBasedUpdateMethodWithNewUniqueKey", testIndexBasedUpdateMethodWithNewUniqueKey),
        ("testInitializationUsingArrayLiteral", testInitializationUsingArrayLiteral),
        ("testInitializationUsingDictionaryLiteral", testInitializationUsingDictionaryLiteral),
        ("testInitializationUsingUnsortedDictionaryAndSortFunction", testInitializationUsingUnsortedDictionaryAndSortFunction),
        ("testInitializationUsingValuesAndKeyProviderClosure", testInitializationUsingValuesAndKeyProviderClosure),
        ("testInitializationUsingValuesAnyKeyPath", testInitializationUsingValuesAnyKeyPath),
        ("testKeyBasedModifications", testKeyBasedModifications),
        ("testKeyBasedRemoval", testKeyBasedRemoval),
        ("testMapValues", testMapValues),
        ("testMovingElements", testMovingElements),
        ("testPopFirstEmpty", testPopFirstEmpty),
        ("testPopFirstNonEmpty", testPopFirstNonEmpty),
        ("testPopLastEmpty", testPopLastEmpty),
        ("testPopLastNonEmpty", testPopLastNonEmpty),
        ("testRemoveAll", testRemoveAll),
        ("testRemoveFirstNonEmpty", testRemoveFirstNonEmpty),
        ("testRemoveLastNonEmpty", testRemoveLastNonEmpty),
        ("testRetrievingElementAtNonExistentIndex", testRetrievingElementAtNonExistentIndex),
        ("testSliceAccess", testSliceAccess),
        ("testSortingWithMutation", testSortingWithMutation),
        ("testSortingWithoutMutation", testSortingWithoutMutation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OrderedDictionaryTests.__allTests__OrderedDictionaryTests),
    ]
}
#endif
